# Generated by Django 3.2.9 on 2021-11-27 08:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Task name', max_length=100)),
                ('deadline', models.DateField(default=datetime.date.today)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='High', help_text='Task Priority', max_length=6)),
                ('is_complete', models.BooleanField(default=False, help_text='Designates whether task is completed or not')),
                ('status', models.CharField(choices=[('Overdue', 'Overdue'), ('Upcoming', 'Upcoming'), ('Today', 'Today')], default='Upcoming', help_text='Task Status', max_length=10)),
                ('is_deleted', models.BooleanField(default=False, help_text='Designates whether task is deleted or not')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Task',
            },
        ),
    ]
